### PR TITLE
performance improvement

### PR DESCRIPTION
**Pull request by joseAlfaro25**
**Please describe the changes this PR makes and why it should be merged:**
Performance improvement:

Some methods were experiencing low performance due to the amount of traversal they were performing. The purpose of this merge is to address two of them.

### CODE REVIEW

**Comment by aidenybai** [comment]
hi @joseAlfaro25, great work! mind setting up a quick benchmark / performance profile to check

**Comment by joseAlfaro25** [comment]
>@aidenybai 
Yes, of course.

**Comment by tobySolutions** [comment]
> >@aidenybai 
> Friend, it will have to be another day. It's already too late where I live, and I just realized it's 3 AM. 
> 

Good job @joseAlfaro25. No problem at all, we'll be expecting your feedback.

**Comment by aidenybai** [comment]
@joseAlfaro25 why was this PR closed?

**Comment by joseAlfaro25** [comment]
Brother, I closed it because I didn't know what type of tests to perform on the code.

**Pull request closed without merging**
