### PR TITLE
Build a virtual whiteboard 613

### PR DESCRIPTION
**Pull request by one2code**
**Please describe the changes this PR makes and why it should be merged:**

Designed and created a virtual whiteboard with in React-TS with Million.js, that allows the user to select their input color and the modes: draw, write, line, erase, undo, and redo. This fulfills the criteria laid out in #613, as part of Million.js 's Hacktoberfest event.

I made a further commit to resolve issues with the way the color input button was being rendered in Chrome vs Firefox. In Chrome, padding was being added by default that crushed the visibility of the selected color inside of the button. I added values specific to Chrome and Firefox to make the button look similar between the two browsers for a more consistent user experience.

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by tobySolutions — COMMENTED** [review]
Hey there @one2code, you didn't use the `block()` function from Million at all 🤔

**Comment by tobySolutions** [comment]
I'm gonna merge this for now, though.

**Comment by one2code** [comment]
@tobySolutions  Is it ok to create another PR with updates? I also found a bug as well.

**Comment by tobySolutions** [comment]
Please go for it @one2code; sorry I think some things I pushed earlier messed up the repo and your PR. Go ahead and make another PR please. Make sure to use more of `block` though, thanks!

**Pull request merged**
