### PR TITLE
Kitchen Sink: Type Racing Game added

### PR DESCRIPTION
**Pull request by izruff**
**Please describe the changes this PR makes and why it should be merged:**

This PR implements the game "type race" where users type quickly to score higher.

**Status**

Closes [#663](https://github.com/aidenybai/million/issues/663)

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by Timonwa — APPROVED** [review]
This looks good to me. And I enjoyed playing the game. Can you resolve your merge conflict so your PR can be merged?

**Comment by izruff** [comment]
@Timonwa thank you! I have resolved it, please check

**Comment by Timonwa** [comment]
@tobySolutions, Can you merge this? It's good to go.

**Review by tobySolutions — APPROVED** [review]
Amazing work! Just please resolve your merge conflicts please. Thank you so much!

**Comment by tobySolutions** [comment]
Also, can you maybe try using the `block` function for some more components?

**Comment by Drex72** [comment]
also @izruff , could you also resolve your merge conflicts also

**Review by tobySolutions — APPROVED** [review]
LGTM!

**Comment by tobySolutions** [comment]
Good job @izruff

**Pull request merged**
