### PR TITLE
fix typo for conflicts in docs:install.mdx

### PR DESCRIPTION
**Pull request by mkanyar**
**Please describe the changes this PR makes and why it should be merged:**
Fix typo for `conflicts` in docs: install.mdx
**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by mkanyar** [comment]
> [CLA assistant check](https://cla-assistant.io/aidenybai/million?pullRequest=538) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=538) before we can accept your contribution.
> 
> **Mike Stephane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=538) it.

I have agreed to the CLA but it seems to not be updating on this page

**Review by tobySolutions — APPROVED** [review]
LGTM

**Comment by tobySolutions** [comment]
> > [CLA assistant check](https://cla-assistant.io/aidenybai/million?pullRequest=538) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=538) before we can accept your contribution.
> > **Mike Stephane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=538) it.
> 
> I have agreed to the CLA but it seems to not be updating on this page

Are you sure you've signed? Can you check again?

**Comment by mkanyar** [comment]
> > > [CLA assistant check](https://cla-assistant.io/aidenybai/million?pullRequest=538) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=538) before we can accept your contribution.
> > > **Mike Stephane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=538) it.
> > 
> > 
> > I have agreed to the CLA but it seems to not be updating on this page
> 
> Are you sure you've signed? Can you check again?

yes I did sign. I tried to re-sign again but no change 

IMG_9219

**Comment by aidenybai** [comment]
lgtm

**Pull request merged**
