### PR TITLE
added Kitchen Sink: A Memory Game

### PR DESCRIPTION
**Pull request by sr2005roy**
issue: #609
added Kitchen Sink: Build A Memory Game using million,js and react. Hope you like it :)
closes: [Kitchen Sink: Build A Memory Game #609](https://github.com/aidenybai/million/issues/609)
images:
image
image
image

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by sr2005roy** [comment]
closes: [Kitchen Sink: Build A Memory Game #609](https://github.com/aidenybai/million/issues/609)

**Comment by sr2005roy** [comment]
hi can you please review and merge the pull request

**Comment by tobySolutions** [comment]
Hey there! Can you check your push? You seem to have merge conflicts.

**Comment by sr2005roy** [comment]
ok i will upgrade it within some time.

**Pull request closed without merging**
