### PR TITLE
Added github user search

### LINKED ISSUE #668: Kitchen Sink : Github User Search
### Describe the feature

I would like to contribute to this repository by creating a Github-user-search application using the Million.js library.
This application will provide a simple and efficient way to search users on github and get their details such as followers ,etc.
**Could you please assign this issue to me:)**

### Additional information

- [ ] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by capsy14**
# Title: Add GitHub User Search and Enhance User Profile #668 

## Description:

This PR adds a new feature to the application that allows users to search for GitHub users and view their profiles. Additionally, it enhances the user profile functionality by displaying the user's followers, following, location, and bio.

## GitHub User Search:

Added a new search feature that allows users to search for GitHub users by their username.
Implemented the search functionality using the GitHub API.
Display search results with user avatars and usernames.
Clicking on a search result takes the user to the corresponding user's profile page.
User Profile Enhancement:

On the user profile page, added a section to display the user's followers and following counts.
Display the user's location and bio if available in their GitHub profile.
Screenshots:
image
image

## Testing:

Performed unit tests for the search functionality.
Manually tested the user profile page to ensure that it displays followers, following, location, and bio correctly.
Thank you :)

Resolves #668

### CODE REVIEW

**Review by Timonwa — CHANGES_REQUESTED** [review]
Hi @capsy14, thank you for your PR. You didn't implement Milion.js in your project. Also, on page load, your details are being shown by default. Can you clear the default? Or add the query as the input value so the users can know that your username brought out the result.

**Comment by capsy14** [comment]
Ok !! let me look into the issue.

**Comment by capsy14** [comment]
Kindly review this 
Thanks :)

**Comment by Timonwa** [comment]
It's OK now. But can you show an error message when a user searches for a username that doesn't exist? Then, we will merge this.

**Comment by capsy14** [comment]
I have added an error message that user is not found if username entered doesn't exist.
@Timonwa Kindly review it.
Thanks :)

**Review by Timonwa — APPROVED** [review]

**Comment by Timonwa** [comment]
nice @capsy14 👍🏽 
This is ready for merge @tobySolutions

**Review by tobySolutions — APPROVED** [review]
LGTM! Thanks @Timonwa.

**Comment by tobySolutions** [comment]
Good job @capsy14!

**Pull request merged**
