### PR TITLE
:hammer: fix

### PR DESCRIPTION
**Pull request by japrozs**
/claim #567

### CODE REVIEW

**Comment by ologbonowiwi** [comment]
This doesn't work. Having a div will break the CSS selector, same as slot breaks currently.

**Comment by tobySolutions** [comment]
Hmm, what do you think @ologbonowiwi, @japrozs?

**Comment by ologbonowiwi** [comment]
I've tried this approach but we'll end having the same issue that we have now (the CSS selector will not account the additional `<div>`, as does not accommodate the additional `<slot>`)

**Comment by rishi-raj-jain** [comment]
There shall be no component as far as I see. <select>s for example shall have no nested items inside them.

**Comment by ologbonowiwi** [comment]
👆🏽 Exactly 

currently 
```
<div>
  // elements
</div>
```
becomes 
```
<slot>
  <div>
    // elements
  </div>
</slot>
```
but as @rishi-raj-jain said, we need to keep the original structure

**Comment by tobySolutions** [comment]
Thanks @rishi-raj-jain, @ologbonowiwi; are you interested in setting up a meeting @ologbonowiwi to go over what your fix does?

**Comment by skushagra9** [comment]
Is this issue solved compeletely ?
If not please assign me

**Pull request closed without merging**
