### PR TITLE
Documentation(i18n): Translate the docs to Spanish

### PR DESCRIPTION
**Pull request by glitch-txs**
**Please describe the changes this PR makes and why it should be merged:**

- [x] Automatic Mode
- [x] Install
- [x] Introduction

### Manual Mode
- [x] Block
- [x] For
- [x] Manual Mode
- [x] Virtualization

### Internals
- [x] Block
- [x] Map Array
- [x] Mount
- [x] Patch
- [x] Render to Template
- [x] String to DOM

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

closes https://github.com/aidenybai/million/issues/907

### CODE REVIEW

**Comment by tobySolutions** [comment]
Awesome work @glitch-txs!! Thanks.

**Comment by glitch-txs** [comment]
thanks! @tobySolutions!
I think it's done, could you review?

For some reason `/es-ES/docs/manual-mode/for` gives me 404 as well on local

**Comment by tobySolutions** [comment]
Awesome!!! Thanks @glitch-txs 🙌🙌🙌. I'll review it in a bit.

**Comment by tobySolutions** [comment]
> thanks! @tobySolutions!
> I think it's done, could you review?
> 
> For some reason `/es-ES/docs/manual-mode/for` gives me 404 as well on local

It does not work in prod as well? I'll check it out and let you know. 

That's certainly weird.

**Comment by glitch-txs** [comment]
haven't tried on prod, will give it one last read to the whole thing just in case

**Comment by glitch-txs** [comment]
there are some warning that are written in English because they are components, may we could make this components to receive a prop with the text so it can be trasnlated on the dif pages
image

**Comment by glitch-txs** [comment]
also this part seems off from main docs, it's talking about the For component but the example shows a block?
image

**Comment by tobySolutions** [comment]
> there are some warning that are written in English because they are components, may we could make this components to receive a prop with the text so it can be trasnlated on the dif pages image

Hmm, do you want to work on that?

**Comment by glitch-txs** [comment]
> Hmm, do you want to work on that?

sure, since it might be breaking change for other languages we can do it in another PR if that's ok

**Comment by tobySolutions** [comment]
> > Hmm, do you want to work on that?
> 
> sure, since it might be breaking change for other languages we can do it in another PR if that's ok

Yeah, much later on. Can you pull latest changes? I just committed something directly to main?

**Comment by tobySolutions** [comment]
Reviewing it now @glitch-txs

**Comment by glitch-txs** [comment]
Thanks! Let me know if there any changes left 🫡

**Comment by tobySolutions** [comment]
> Thanks! Let me know if there any changes left 🫡

Ok, so I fixed the `For` page issue. I'm making a push now

**Comment by tobySolutions** [comment]
Great work @glitch-txs!! Thanks 🙌

**Review by tobySolutions — APPROVED** [review]
LGTM!! Thanks!

**Pull request merged**
