### PR TITLE
Feature : Add Drawing Canvas.

### PR DESCRIPTION
**Pull request by Yash7426**
**Please describe the changes this PR makes and why it should be merged:**
Added a drawing canvas built using million.js and React. It allows user to use multiple colors for drawing. It also saves the work in localstorage. 

**Status**
Closes: [kitchenSink/Drawing-canvas#619](https://github.com/aidenybai/million/issues/619)

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
> Hi @Yash7426 , thank you for your PR. Everything looks good to me @tobySolutions.

Awesome! let me check it out

**Review by tobySolutions — APPROVED** [review]
LGTM! Could you maybe edit make the canvas white to start with? Thanks @Timonwa 

Screenshot 2023-10-03 at 18 16 10

**Comment by Yash7426** [comment]
@tobySolutions sure!!

**Comment by tobySolutions** [comment]
> @tobySolutions sure!!

Awesome!

**Comment by tobySolutions** [comment]
I figured it out.

**Comment by Yash7426** [comment]
@tobySolutions Fixed the bug.

**Comment by tobySolutions** [comment]
> @tobySolutions Fixed the bug.

Awesome, good work!

**Pull request merged**
