### PR TITLE
Playground: Preset Passed Via Search Param in URL

### PR DESCRIPTION
**Pull request by ethanniser**
for #365 

Got to a decent point, required some kinda wild useEffect stuff to keep the url + atom in sync. Jotai does provide a `atomWithHash`, but [unfortunately doesn't support Next 13 / app router](https://jotai.org/docs/guides/nextjs#in-next-js-13)

Also found a bug where if you select a new framework while the current one is loading it will show the new files, but use the previous start command.

So I'll work on fixing that tomorrow, but would appreciate any feedback on what I did so far. Thanks!

*also at some point the vite-react example/default code stopped previewing idk whats up with that*

### CODE REVIEW

**Comment by ethanniser** [comment]
also I am so confused why all the commits from that last pr are on here

**Comment by tobySolutions** [comment]
> also I am so confused why all the commits from that last pr are on here

Hey @ethanniser, has this issue with the commits still on or have you resolved it?

**Comment by ethanniser** [comment]
> > also I am so confused why all the commits from that last pr are on here
> 
> Hey @ethanniser, has this issue with the commits still on or have you resolved it?

it was closed #364

**Comment by tobySolutions** [comment]
> > > also I am so confused why all the commits from that last pr are on here
> > 
> > Hey @ethanniser, has this issue with the commits still on or have you resolved it?
> 
> it was closed #364

Oh ok, awesome!

**Pull request closed without merging**
