### PR TITLE
Hover & Focus state for Social Icons

### PR DESCRIPTION
**Pull request by adetyaz**
**Please describe the changes this PR makes and why it should be merged:**
This solve the issue #649 

**Status**

- [ ] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by adetyaz** [comment]
Hey @tobySolutions,
I had an issue when trying to make sure only the changes I made were committed so I just did it all over again when I couldn't solve the issue

**Review by tobySolutions — APPROVED** [review]
LGTM!

**Comment by tobySolutions** [comment]
What's the. advantage of the raw svg code over using React icons, please? @adetyaz

**Review by tobySolutions — COMMENTED** [review]
I think you can make the svgs an exportable component that you can come use here instead of having all the svg code be here; thank you.

**Comment by adetyaz** [comment]
Noted @tobySolutions I will do that and update.

I used SVG because that was that's what I saw when digging through the Nextra documentation

**Comment by tobySolutions** [comment]
> Noted @tobySolutions I will do that and update.
> 
> I used SVG because that was that's what I saw when digging through the Nextra documentation

Awesome! Thanks.

**Comment by tobySolutions** [comment]
Oh, you haven't made the updates yet?

**Comment by adetyaz** [comment]
> Oh, you haven't made the updates yet?

Not yet, I'll be doing that soon. I'd like to know if I should create an icons folder in the components folder and put each one there since the have different svg values that can't be changed via props

**Comment by tobySolutions** [comment]
Any updates on this @adetyaz?

**Comment by adetyaz** [comment]
Yes I'll be pushing my updates in about an hour, I was waiting for a response on the question I asked

**Comment by adetyaz** [comment]
@tobySolutions It has been updated

**Comment by tobySolutions** [comment]
Can you please sign the CLA? @adetyaz

**Comment by adetyaz** [comment]
Can you please point me to it @tobySolutions

**Comment by tobySolutions** [comment]
> [CLA assistant check](https://cla-assistant.io/aidenybai/million?pullRequest=670) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aidenybai/million?pullRequest=670) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aidenybai/million?pullRequest=670) it.

@adetyaz

**Comment by adetyaz** [comment]
done @tobySolutions

**Comment by tobySolutions** [comment]
> done @tobySolutions

Awesome! Good job @adetyaz

**Review by tobySolutions — APPROVED** [review]
LGTM!!

**Pull request merged**
