### PR TITLE
Remove Unnecessary dependencies

### PR DESCRIPTION
**Pull request by tobySolutions**
Resolves issue #310 

Please review accordingly Maintainers

**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
@tobySolutions can you `pnpm i` inside `packages/react` to update the lockfile?

**Comment by tobySolutions** [comment]
> @tobySolutions can you `pnpm i` inside `packages/react` to update the lockfile?

I might need to make the PR from my machine. I just tried to edit the file here on GitHub. Let me just do that.

**Comment by tobySolutions** [comment]
> @tobySolutions can you `pnpm i` inside `packages/react` to update the lockfile?

Check it now Aiden

**Review by QuiiBz — APPROVED** [review]
Looks good, thanks!

**Comment by tobySolutions** [comment]
> Looks good, thanks!

Awesome! Thanks Tom.

**Pull request merged**
