### PR TITLE
feat: add bounty cards

### PR DESCRIPTION
**Pull request by zcesur**
added a grid of cards beneath the callout that displays the 2 most recent bounties (excluding inactive ones)

also revamped the callout and linked it to your bounty board on algora (which displays some extra info like amounts & claims)

always happy to add any other info you'd like to see in your board, but also feel free to revert it back if you prefer otherwise!

## Before

Dark | Light
:-----:|:-----:
 | 

## After

Dark | Light
:-----:|:-----:
 | 

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
this. is. AMAZING

**Comment by tobySolutions** [comment]
Yeah, this is amazing!!!

**Comment by zcesur** [comment]
glad y'all liked it :heart:

do you guys require a cla for non-core contributions as well?

also not sure why the deployment is failing

**Comment by tobySolutions** [comment]
> glad y'all liked it :heart:
> 
> do you guys require a cla for non-core contributions as well?
> 
> also not sure why the deployment is failing

I think this is the reason why:

**Comment by tobySolutions** [comment]
> glad y'all liked it :heart:
> 
> do you guys require a cla for non-core contributions as well?
> 
> also not sure why the deployment is failing

Regarding the CLA thing, I think @aidenybai can answer that.

**Comment by aidenybai** [comment]
@zcesur we require CLA for all contributions!

**Pull request merged**
