### PR TITLE
doc-Translate the Foundation page to French  #904

### LINKED ISSUE #904: 📝 Documentation(i18n): Translate the Foundation page to French
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have searched for [related issues](https://github.com/aidenybai/million/issues) and found none that matched my issue.

### Overview

Translate the [Foundation Page](https://million.dev/foundation) to French; go to [foundation.fr-FR.mdx](https://github.com/aidenybai/million/blob/main/website/pages/foundation.fr-FR.mdx) and make the translations from there.

Screenshot 2024-01-23 at 16 52 54

### Additional Info

- You can come into the docs channel in the [Discord Server](https://million.dev/chat) for further information. Do translate the front-matter as well. 

- Use an informal tone, not too informal though

- Also, checkout the [Contriibuting Guide](https://github.com/aidenybai/million/blob/main/.github/CONTRIBUTING.md) incase you want to set up Million locally

### PR DESCRIPTION
**Pull request by geoffreylgv**
**Please describe the changes this PR makes and why it should be merged:**
Documentation(i18n): Translate the Foundation page to French closes #904
**Status**

- [ ] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by geoffreylgv** [comment]
Overview of the french version

image

**Comment by tobySolutions** [comment]
Hey there, @geoffreylgv. Can you pull latest changes from main?

**Comment by geoffreylgv** [comment]
> Hey there, @geoffreylgv. Can you pull latest changes from main?

Ok

**Comment by tobySolutions** [comment]
> > Hey there, @geoffreylgv. Can you pull latest changes from main?
> 
> Ok

Oh ok, awesome. Thanks. Push again after pulling the changes

**Comment by geoffreylgv** [comment]
> > > Hey there, @geoffreylgv. Can you pull latest changes from main?
> > 
> > 
> > Ok
> 
> Oh ok, awesome. Thanks. Push again after pulling the changes

All good now @tobySolutions

**Comment by tobySolutions** [comment]
LGTM @geoffreylgv. Great work.

**Comment by geoffreylgv** [comment]
> LGTM @geoffreylgv. Great work.

Thanks

**Pull request merged**
