### PR TITLE
Added BmiCalculator.jsx file for kitchen sink

### LINKED ISSUE #752: Kitchen Sink: BMI Calculator
### Describe the feature

I would like to implement the **BMI Calculator** feature!

- It will take inputs of **Age, Gender, Height, and Weight** from the user.
- Based on the input from the user it will calculate and display **BMI** along with **labels** such as **Underweight, Normal, Overweight, etc**

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by rakshixh**
User have to input their age, gender, height in feet and inch also weight. Based on that BMI is given along with category such as underweight, overweight, normal, etc.

Fixes #752

### CODE REVIEW

**Comment by rakshixh** [comment]
#752

**Review by tobySolutions — APPROVED** [review]
LGTM!

**Comment by tobySolutions** [comment]
Can you please review the responsiveness on mobile @rakshixh?

**Comment by rakshixh** [comment]
Sure @tobySolutions will update you once the responsiveness is reviewed!

**Comment by rakshixh** [comment]
Hey, @tobySolutions made changes to the BMI calculator file for responsiveness. Also deleted the count-down timer file so that for this issue only the bmi file can be there in the commit as you requested.

**Comment by tobySolutions** [comment]
Thanks @rakshixh, reviewing now.

**Review by tobySolutions — APPROVED** [review]
LGTM! Good work @rakshixh.

**Pull request merged**
