### PR TITLE
Placed Macro Docs Inside Internals Folder

### LINKED ISSUE #482: bug: Macro doc misplaced
**Describe the bug**

**To Reproduce**
1. Go to 'Million.dev'
2. Click on '/docs'
3. Scroll down to 'API Reference > below Internals'

**Expected behavior**
To be inside the [internals/macro.mdx] folder

**Screenshots**
Screenshot 2023-07-14 at 14 00 02

**Device (please complete the following information):**
 - OS [e.g. iOS]
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest you can get

**Additional context**

### PR DESCRIPTION
**Pull request by TreciaKS**
**Please describe the changes this PR makes and why it should be merged:**
Closes #482 
I moved the Macro doc inside the internals folder for structure consistency :0

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
image

Good job @TreciaKS! Thank you.

**Review by tobySolutions — APPROVED** [review]
Good job! LGTM.

**Comment by TreciaKS** [comment]
Thanks, Tobi! First of many contributions :)

**Comment by aidenybai** [comment]
Wait, isn't this supposed to be part of the react api...

**Comment by TreciaKS** [comment]
No wait, I just noticed this myself :0
Reason for this issue was that it kind of looks unneat underneath the <internals> menu and I thought to move it there :0

I'll close this issue and PR.

**Pull request closed without merging**
