### PR TITLE
Kitchen Sink: Build A Memory Game added

### PR DESCRIPTION
**Pull request by sr2005roy**
**Please describe the changes this PR makes and why it should be merged:**
issue: #609
added Kitchen Sink: Build A Memory Game using million,js and react. Hope you like it :)
closes: [Kitchen Sink: Build A Memory Game ](https://github.com/aidenybai/million/issues/609)
images::
Screenshot 2023-10-03 191003
Screenshot 2023-10-03 191153
Screenshot 2023-10-03 191124

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by sr2005roy** [comment]
Please check and merge the PR :)

**Comment by tobySolutions** [comment]
Hey @sr2005roy. Thanks. for this! Can you maybe remove the css file and move all your styling to the style.css? Feel free to use comments to separate out your own styling.

**Comment by tobySolutions** [comment]
Also, your images are not coming up. Have you considered deploying them somewhere?

**Comment by sr2005roy** [comment]
That's what which gave conflict last time

**Comment by tobySolutions** [comment]
> That's what which gave conflict last time

Hmm, I don't understand.

**Comment by sr2005roy** [comment]
made the changes :)

**Comment by tobySolutions** [comment]
> made the changes :)

Awesome! Checking it out now.

**Comment by sr2005roy** [comment]
is everything good ??

**Comment by tobySolutions** [comment]
Um, I think something else is wrong:


Uploading Screen Recording 2023-10-04 at 23.45.22.mov…

**Comment by tobySolutions** [comment]
https://github.com/aidenybai/million/assets/96334363/d9cc3e6b-9969-40e9-88d8-d7dded59e46d

**Comment by sr2005roy** [comment]
is the issue corrected t your side?
please check once :)

**Comment by tobySolutions** [comment]
I think instead of using relative paths to the images, you should try using absolute paths instead

**Comment by sr2005roy** [comment]
@tobySolutions
is the issue corrected at your side?
please check once :)

**Comment by Timonwa** [comment]
Hi @sr2005roy ,  there is a bug in this game. Some tile don't close.  And some matches do not happen. And could you add a reset button? 

https://github.com/aidenybai/million/assets/63044364/404a29bc-e020-48e4-9c6d-48e16e787145

https://github.com/aidenybai/million/assets/63044364/3ca4bdb3-18b6-46fd-95f6-05b46d9cbc5e

**Comment by sr2005roy** [comment]
Solved all the bugs
resolved conflicts which appaired 
Also added the reset button 

https://github.com/aidenybai/million/assets/122456380/a3b6ccd5-082e-4715-84ff-c2eef8316e70

@tobySolutions 
Hopefully it works well and you like it :)

**Comment by sr2005roy** [comment]
Kindly check I have resolved all the conflicts

**Comment by tobySolutions** [comment]
Hey @sr2005roy, can you maybe resolve your merge conflicts, please? Thank you!

**Comment by sr2005roy** [comment]
Done bro
Its actually arising as many new merges are been performed so style.css gets conflicts.
Please have a look at this PR :)
 @tobySolutions

**Comment by tobySolutions** [comment]
Hey there, you seem to still have conflicts and I tried resolving them, but, I think I broke it @sr2005roy; could you just please make another PR?

**Comment by Timonwa** [comment]
Hi @sr2005roy, the issues were resolved and the game working right, which is great, but sadly, Tobi couldn't resolve it. Pls, don't feel discouraged, to open a new PR again. ❤️

**Pull request closed without merging**
