### PR TITLE
Feat polling app

### LINKED ISSUE #615: Kitchen Sink: Build A Real-time Polling App
Build a polling app that displays real-time results that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

### PR DESCRIPTION
**Pull request by UzairNoman**
**Please describe the changes this PR makes and why it should be merged:**
Added a RealTimePolling app built using million.js and React. It allows users to vote and see the progress through numbers and simple progress bar.

**Status**
Closes #615

- [ x] Code changes have been tested against prettier, or there are no code changes
- [x ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Timonwa** [comment]
@UzairNoman, this is nice.  But there is no button to clear/reset the form or delete an option.  I had to refresh the page before I could create a new poll.

Can you add them? Then we can merge this PR.

**Comment by UzairNoman** [comment]
Hi @Timonwa, there is a blocker to making your suggested changes, please have a look at the issue I created #680. Since this is the issue with block() wrapper. Can I implement this without wrapping the function in block()? 

Let me know what you think. 

Thanks

**Comment by tobySolutions** [comment]
Hey there @UzairNoman, could you please share a screen recording of the problem and maybe share a link to your code? Thanks

**Comment by tobySolutions** [comment]
Hey there @UzairNoman, could you please share a screen recording of the problem and maybe share a link to your code? Thanks

**Comment by UzairNoman** [comment]
Hi @tobySolutions, I have mentioned the blocker in screen sharing in issue https://github.com/aidenybai/million/issues/680. But I think you have closed the polling app feature, this feature is almost completed, just need a reset button as @Timonwa suggested. I will implement it soon we find some solution to #680.

**Comment by Timonwa** [comment]
Oh. @UzairNoman, sorry about that. Unfortunately, accepted projects have to be using Millionjs. You can try again when the issue has been resolved.

**Pull request closed without merging**
