### PR TITLE
add ai image generator

### LINKED ISSUE #651: AI Image Generator Using OpenAI
### Describe the feature

An AI Image Generator powered by OpenAI and Millions.js is a cutting-edge tool designed to create stunning and unique images with the help of artificial intelligence. This project combines the power of OpenAI's natural language understanding and Millions.js capabilities to generate visually captivating and imaginative artwork.

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by darshbaxi**
## FIXES #651
**I made an AI Image Generator using Million.js and Openai API. This project combines the power of OpenAI's natural language understanding and Millions.js capabilities to generate visually captivating and imaginative artwork.**

### Screenshot:
image

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Hey there @darshbaxi, I think there's an API with your API keys or something:


https://github.com/aidenybai/million/assets/96334363/e9d7658f-3a0c-446c-8dd1-84a515c61f30

Screenshot 2023-10-05 at 23 26 54

**Comment by darshbaxi** [comment]
@tobySolutions  I will fix this:)

**Comment by darshbaxi** [comment]
@tobySolutions Bug Fixes. Please review my PR again:)

**Comment by tobySolutions** [comment]
Ok, let me review it again.

**Comment by tobySolutions** [comment]
Hey there @darshbaxi, this might be working locally for you, but, due some facts around the API 
key not being available in production, it might prevent this from working out; maybe try using a .env or you can look up workarounds


Screenshot 2023-10-06 at 23 09 20

**Pull request closed without merging**
