### PR TITLE
feat: kitchen sink/movie finder

### LINKED ISSUE #702: Kitchen sink: a movie finder app

### PR DESCRIPTION
**Pull request by ForJessicaSake**
**Please describe the changes this PR makes and why it should be merged:**

This PR introduces a new feature in the Kitchen Sink project that enables users to search for movies based on their queries using Million .

Resolves #702 

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
- [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Hello there @ForJessicaSake, there are some issues in production with the movie API you are using. Due to the fact that it is required that you need to the API keys to an env or something in production. Could you maybe explore other options among public APIs or just hard-code the data and try a different approach? Thanks!

**Comment by ForJessicaSake** [comment]
@tobySolutions thanks for that. I changed keys and made a new push for the changes, this should work on production

**Comment by tobySolutions** [comment]
> @tobySolutions thanks for that. I changed keys and made a new push for the changes, this should work on production

Hmm, oh ok. Let me review. Thanks!

**Review by tobySolutions — APPROVED** [review]
LGTM! Amazing work Jessica!

**Comment by ForJessicaSake** [comment]
thanks

**Pull request merged**
