### PR TITLE
completed the revamp

### LINKED ISSUE #791: Revamp the Kitchen Sink Website
### Description:
I would like to suggest Revamping the kitchen sink website as it doesnt look good on mobile and it affects responsiveness.With the increasing number of Kitchen Sink projects,we'd have to find a way to layout all the projects more effectively and i would like to be a part of that.

Benefits:
It enhances responsiveness
Provides motivation by allowing users to see their improvements over time in a more beautified manner.

Additional Information:
 I believe that revamping the website to enhance mobile responsiveness and project layout will lead to improved user satisfaction, increased mobile traffic, and better representation of the Kitchen Sink projects.

Please assign this issue to me :)

### PR DESCRIPTION
**Pull request by Drex72**
### **Description of Changes:**

In this PR, I have Revamped the Kitchen Sink Website to have better User Experience and to look nicer

Resolves #791 

**Status**

- [ x] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

Additional Note:

The integration of this ESLint plugin is a crucial step in maintaining and improving the quality of our codebase. I believe that it will have a substantial positive impact on our development process, and I am eager to receive feedback and collaborate with the team to ensure a seamless and productive experience. Thank you for considering this PR.

### CODE REVIEW

**Review by Timonwa — APPROVED** [review]
Nice one @Drex72 . Can you make the menu close on-click?

**Comment by Drex72** [comment]
> Nice one @Drex72 . Can you make the menu close on-click?

Oh, yh
I must have skipped that
i'd fix it now

**Comment by Drex72** [comment]
@Timonwa  Just fixed it

**Comment by tobySolutions** [comment]
You have merge conflicts @Drex72; can you check it out it, please?

**Comment by Drex72** [comment]
> You have merge conflicts @Drex72; can you check it out it, please?

Alright
i'd work on it now

**Pull request closed without merging**
