### PR TITLE
 whack a mole game added

### PR DESCRIPTION
**Pull request by Yash9276**
**Please describe the changes this PR makes and why it should be merged:**
image

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Good job @Yash9276, I'm reviewing it now.

**Review by tobySolutions — COMMENTED** [review]
Did you try using the `block` function on the `WhackAMole` component?

**Comment by Yash9276** [comment]
I tried to integrate but it was showing some error

**Comment by Timonwa** [comment]
> Can you please check your code out @Yash9276, it doesn't seem to be working.

@tobySolutions, I think the game works as it should. It just needs a better output message. @Yash9276 Can you show the result under the `Start` button? Increase the font size, and font weight and change the color of the result message so it can be easily visible to the player when the game ends.

And instead of just saying `time out`, you could say `Time out! you scored 10 points.` or something like that

**Comment by tobySolutions** [comment]
> > Can you please check your code out @Yash9276, it doesn't seem to be working.
> 
> @tobySolutions, I think the game works as it should. It just needs a better output message. @Yash9276 Can you show the result under the `Start` button? Increase the font size, and font weight and change the color of the result message so it can be easily visible to the player when the game ends.
> 
> And instead of just saying `time out`, you could say `Time out! you scored 10 points.` or something like that

Awesome! Thank you Timonwa. Currently reviewing the PR.

**Comment by tobySolutions** [comment]
Could you maybe resolve your merge conflicts @Yash9276?

**Pull request closed without merging**
