### PR TITLE
fix: [#336] Increased clickable area for Open Demo button

### PR DESCRIPTION
**Pull request by giri-madhan**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Hey @giri-madhan! How are you? Great job, however there is still a problem when I want to close the demo.

[Screencast from 05-05-2023 11:35:09 AM.webm](https://user-images.githubusercontent.com/96334363/236436290-7fb2a672-67dd-400e-a123-7994d3865c33.webm)

**Comment by giri-madhan** [comment]
> Hey @giri-madhan! How are you? Great job, however there is still a problem when I want to close the demo.
> 
>  Screencast.from.05-05-2023.11.35.09.AM.webm

Hi @tobySolutions, thank you for taking the time to share the video of the issue. I have updated the style for the close button and now the entire button is clickable for both the open and close buttons.

**Comment by tobySolutions** [comment]
> > Hey @giri-madhan! How are you? Great job, however there is still a problem when I want to close the demo.
> > Screencast.from.05-05-2023.11.35.09.AM.webm
> 
> Hi @tobySolutions, thank you for taking the time to share the video of the issue. I have updated the style for the close button and now the entire button is clickable for both the open and close buttons.

OKay cool. let me check it out.

**Comment by tobySolutions** [comment]
Great job @giri-madhan!!

**Review by tobySolutions — APPROVED** [review]
LGTM!

**Comment by giri-madhan** [comment]
Thank you  🙂

**Comment by aidenybai** [comment]
LGTM!!

**Pull request merged**
