### PR TITLE
Recipie Meal Planner

### LINKED ISSUE #601: Kitchen Sink: Build A Recipe Finder
Build a recipe finder app that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

### LINKED ISSUE #629: Kitchen Sink: Build A Recipe Meal Planner
Build a meal planning app that suggests recipes and generates shopping lists that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

### PR DESCRIPTION
**Pull request by Roar022**
# Description of Changes:

1. **Recipe Search Functionality:** The PR introduces a new feature that allows users to search for recipes. This is a significant enhancement as it enhances the user's ability to find specific recipes quickly and efficiently.

2. **Recipe Listing:** Upon searching, the user receives a list of recipes as a result. This list is a crucial part of the change as it helps users browse through various recipe options based on their search query.

3. **Add to Cart Feature:** Each recipe in the list comes with two options, "add to cart" and "show instruction." The "add to cart" feature enables users to add a selected recipe to their meal planner's shopping cart. This is a valuable feature for users who want to plan their meals and shopping lists.

4. **Show Information Feature:** The "show instruction" button, when clicked, displays a list of added ingredients for the selected recipe. This feature provides users with a quick overview of the ingredients required for a recipe, aiding them in meal planning.

5. **Shopping Cart Functionality:** Users can access their shopping cart, which likely stores all the recipes they've added. Within the cart, users have the option to view additional information about the recipes they've added. This allows users to review their meal plans easily.

6. **Remove from Cart Option:** Additionally, the PR introduces a "remove from cart" option within the shopping cart. This is essential for users who may change their meal plans or decide not to include specific recipes, giving them the flexibility to manage their cart effectively.

# Why it Should be Merged:

1. **Enhanced User Experience:** The changes in this PR significantly enhance the user experience by providing a more intuitive and efficient way to plan meals and manage recipes.

2. **Meal Planning Convenience:** With the "add to cart" feature and the ability to view ingredient information, users can effectively plan their meals and create shopping lists, making it a valuable addition for anyone using the application.

3. **Flexibility and Usability:** The "remove from cart" option and the ability to view ingredients provide users with flexibility and the necessary information to make informed decisions about their meal plans.

# Resolves #629

# Demo Video

https://github.com/aidenybai/million/assets/111555339/faf07c4d-0e5f-440d-b1f9-b16ef843193f

Resolves #601 

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by Timonwa — CHANGES_REQUESTED** [review]
Hi @Roar022,
1. when I click on `show instructions`, it only shows the ingredients. It doesn't show the instructions to prepare it. Could you fix that?
2. Could you use Millon's [`<For />`  API ](https://million.dev/docs/for) to render the recipes if you don't encounter errors using it?
3. Then the text on the cart section doesn't show well on light mode:
FireShot Capture 028 - Million Kitchen Sink - million-kitchen-sink-rnhtbqizc-millionjs vercel app

**Comment by Roar022** [comment]
> Hi @Roar022,
> 
> 1. when I click on `show instructions`, it only shows the ingredients. It doesn't show the instructions to prepare it. Could you fix that?
> 2. Could you use Millon's [`<For />`  API ](https://million.dev/docs/for) to render the recipes if you don't encounter errors using it?
> 3. Then the text on the cart section doesn't show well on light mode:
>    FireShot Capture 028 - Million Kitchen Sink - million-kitchen-sink-rnhtbqizc-millionjs vercel app

ok, i will try to fix it.

**Comment by Roar022** [comment]
do i display only instructions or combination of instructions and ingredients?

**Comment by Timonwa** [comment]
> do i display only instructions or combination of instructions and ingredients?

Display both of them. As both are important. 😄

**Comment by Roar022** [comment]
@Timonwa I have made the required changes. Please review it.

**Comment by Timonwa** [comment]
Awesome job @Roar022.
This is ready for merge @tobySolutions

**Review by tobySolutions — COMMENTED** [review]
Hey there! Did you try using the `block` function on the `RecipeFinder` component?

**Comment by Roar022** [comment]
> Hey there! Did you try using the `block` function on the `RecipeFinder` component?

Yes just did. Its working fine. Should i add it?

**Comment by tobySolutions** [comment]
> > Hey there! Did you try using the `block` function on the `RecipeFinder` component?
> 
> Yes just did. Its working fine. Should i add it?

Sure thing!

**Comment by tobySolutions** [comment]
> > > > Hey there! Did you try using the `block` function on the `RecipeFinder` component?
> > > 
> > > 
> > > Yes just did. Its working fine. Should i add it?
> > 
> > 
> > Sure thing!
> 
> just added block, please review it. :)

Awesome! Good work @Roar022

**Review by tobySolutions — APPROVED** [review]
LGTM! Merging now

**Pull request merged**
