### PR TITLE
fix: better syntax support

### LINKED ISSUE #936: Support for the experimental syntax 'importAttributes' isn't currently enabled
### What version of `million` are you using?

3.0.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Arc

### Describe the Bug

I tried upgrading my website from v `2.6.4` to `3.0.2` but started getting this error.

```bash
unhandledRejection SyntaxError: /Users/jahir/dev/jahir/website/.contentlayer/generated/index.mjs: Support for the experimental syntax 'importAttributes' isn't currently enabled (7:43):

   5 | // NOTE During development Contentlayer imports from `.mjs` files to improve HMR speeds.
   6 | // During (production) builds Contentlayer it imports from `.json` files to improve build performance.
>  7 | import allBlogs from './Blog/_index.json' assert { type: 'json' }
     |                                           ^
   8 |
   9 | export { allBlogs }
  10 |

Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing.
```

### What's the expected result?

The build should be completed normal and successfully

### Link to Minimal Reproducible Example

I don't have one, sorry. But here's a PR with the changes I did: https://github.com/jahirfiquitiva/jahir.dev/pull/73

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lxsmnsyc**
Makes it so that the babel plugin supports experimental syntax.

- fixes #936

### CODE REVIEW

**Comment by jahirfiquitiva** [comment]
hey @lxsmnsyc , maybe `importAssertions` is needed too? I just got another error mentioning that one 🤔 

```bash
⨯ unhandledRejection: SyntaxError: /Users/jahir/dev/jahir/website/.contentlayer/generated/Blog/_index.mjs: Support for the experimental syntax 'importAttributes' isn't currently enabled (3:67):

  1 | // NOTE This file is auto-generated by Contentlayer
  2 |
> 3 | import _23ChangesIn_2023Mdx from './_23-changes-in-2023.mdx.json' assert { type: 'json' }
    |                                                                   ^
  4 | import aFreshStartMdx from './a-fresh-start.mdx.json' assert { type: 'json' }
  5 | import aPrioriCareMdx from './a-priori-care.mdx.json' assert { type: 'json' }
  6 | import astroReadingTimeMdx from './astro-reading-time.mdx.json' assert { type: 'json' }

Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing.
    at toParseError (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parse-error.ts:74:19)
    at JSXParserMixin.raise (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/tokenizer/index.ts:1487:19)
    at JSXParserMixin.expectOnePlugin (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/tokenizer/index.ts:1552:18)
    at JSXParserMixin.maybeParseImportAttributes (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:3284:14)
    at JSXParserMixin.parseImportSourceAndAttributes (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:3109:10)
    at JSXParserMixin.parseImportSpecifiersAndAfter (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:3100:17)
    at JSXParserMixin.parseImport (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:3066:17)
    at JSXParserMixin.parseStatementContent (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:578:25)
    at JSXParserMixin.parseStatementLike (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:417:17)
    at JSXParserMixin.parseModuleItem (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:354:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:1385:16)
    at JSXParserMixin.parseBlockBody (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:1359:10)
    at JSXParserMixin.parseProgram (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:213:10)
    at JSXParserMixin.parseTopLevel (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/statement.ts:195:25)
    at JSXParserMixin.parse (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/parser/index.ts:45:10)
    at parse (/Users/jahir/dev/jahir/website/node_modules/@babel/parser/src/index.ts:66:38)
    at parser (/Users/jahir/dev/jahir/website/node_modules/@babel/core/src/parser/index.ts:28:19)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/jahir/dev/jahir/website/node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
    at normalizeFile.next (<anonymous>)
    at run (/Users/jahir/dev/jahir/website/node_modules/@babel/core/src/transformation/index.ts:39:36)
    at run.next (<anonymous>)
    at transform (/Users/jahir/dev/jahir/website/node_modules/@babel/core/src/transform.ts:29:20)
    at transform.next (<anonymous>)
    at step (/Users/jahir/dev/jahir/website/node_modules/gensync/index.js:261:32)
    at /Users/jahir/dev/jahir/website/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/jahir/dev/jahir/website/node_modules/gensync/index.js:223:11)
    at cb (/Users/jahir/dev/jahir/website/node_modules/gensync/index.js:189:28)
    at /Users/jahir/dev/jahir/website/node_modules/@babel/core/src/gensync-utils/async.ts:90:7
    at /Users/jahir/dev/jahir/website/node_modules/gensync/index.js:113:33
    at step (/Users/jahir/dev/jahir/website/node_modules/gensync/index.js:287:14)
    at /Users/jahir/dev/jahir/website/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/jahir/dev/jahir/website/node_modules/gensync/index.js:223:11) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'MissingOneOfPlugins',
  loc: Position { line: 3, column: 66, index: 119 },
  pos: 119,
  missingPlugin: [ 'importAttributes', 'importAssertions' ]
}
```

**Comment by lxsmnsyc** [comment]
@jahirfiquitiva `importAssertions` is actually a deprecated syntax and the `importAttributes` is its successor. Is there any reason that it is still being used?

**Comment by jahirfiquitiva** [comment]
@lxsmnsyc thanks for the info, the error mentions both `missingPlugin: [ 'importAttributes', 'importAssertions' ]`, so I think having `importAttributes` only will be enough then 😅🙌

**Comment by lxsmnsyc** [comment]
seems to me that the cause of the issue was Contentlayer, perhaps it can be moved upstream?

**Comment by jahirfiquitiva** [comment]
@lxsmnsyc unfortunately Contentlayer development is currently on pause, so it will be hard for this to get fixed there anytime soon. Besides, everything worked fine with million `2.6.4`, it just got broken after the upgrade to `3.0.2`

**Pull request merged**
