### PR TITLE
Markdown editor

### PR DESCRIPTION
**Pull request by cyberviking5**
**Please describe the changes this PR makes and why it should be merged:**
I made the markdown editor in ts using marked library along with using million in ts. Please feel free to contact me if you to make any changes :) 
Screenshot from 2023-10-02 22-48-30
Screenshot from 2023-10-02 22-48-56

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
Looks like you didn't install using pnpm. Could you run `pnpm i`?

**Comment by cyberviking5** [comment]
@aidenybai please tell what should i do now after running pnpm i and pnpm run cleanup as it is still failing some checks .

**Comment by tobySolutions** [comment]
Hey there @cyberviking5, can you maybe recheck your PR? Run tests locally, run build and stuff like that?

**Comment by Timonwa** [comment]
@cyberviking5 run `pnpm build` on your local machine. If it fails, please check the errors it gave you and try fixing them. If after trying to fix them and are still unsuccessful, please feel free to screenshot errors and share it with us here or on Discord.

**Comment by tobySolutions** [comment]
Hey @cyberviking5, for some reason, the preview doesn't work as expected, it is the same as the one from the editor:

Screenshot 2023-10-03 at 16 13 24

**Comment by cyberviking5** [comment]
@tobySolutions this initial is for the reference on how to write the markdown once you clear the editor you can use the editor like a normal markdown editor and the preview shows the correct output . If you want i can remove this initial words for reference . If you have any more issues please feel free to contact me :)

**Comment by cyberviking5** [comment]
@tobySolutions please review the changes now and please let me know if you want any more changes :)

**Comment by tobySolutions** [comment]
> @tobySolutions please review the changes now and please let me know if you want any more changes :)

Awesome! Checking it out now

**Comment by tobySolutions** [comment]
Awesome! Good job @cyberviking5!

**Comment by tobySolutions** [comment]
I think it'll be much better if you only committed that file, cos at the moment it shows that 20 files were changed. What do you think? @cyberviking5?

**Comment by tobySolutions** [comment]
Hey there! Great work so far! Could you maybe just resolve your merge conflicts and then I can go ahead and close this off?

**Comment by cyberviking5** [comment]
sure @tobySolutions I will remove the conflicts please give me some time :)

**Comment by cyberviking5** [comment]
please check now @tobySolutions and please let me know in case of any changes :)

**Comment by tobySolutions** [comment]
Good job @cyberviking5! Reviewing now

**Review by tobySolutions — COMMENTED** [review]
Can you maybe just fix the responsiveness with a flex-direction of column on mobiles, it gets cut out of the screen on mobile phones! Thank you very much for the great work!! @cyberviking5

**Comment by tobySolutions** [comment]
When you have the time, could you resolve the responsiveness issues please @cyberviking5?

**Comment by tobySolutions** [comment]
There you go @cyberviking5:


https://github.com/aidenybai/million/assets/96334363/356d83ba-ddc5-43d8-8a2b-ca051410be01

**Review by tobySolutions — CHANGES_REQUESTED** [review]
Could you fix the responsiveness issues you have on mobile @cyberviking5?

**Pull request closed without merging**
