### PR TITLE
Added CountDownTimer.jsx file also added svg files in assets folder.

### PR DESCRIPTION
**Pull request by rakshixh**
Added the following functionalities:

- Timer
- Start timer
- Stop timer
- Flag enteries
- Restart
- Clear Entries

### CODE REVIEW

**Comment by rakshixh** [comment]
#751

**Comment by tobySolutions** [comment]
Can you please review the responsiveness on mobile @rakshixh?

**Comment by rakshixh** [comment]
Sure @tobySolutions will update you once responsiveness is reviewed.

**Comment by rakshixh** [comment]
Hey @tobySolutions please check with the new commit in the branch **rakshixh:feat-kitchen-sink-count-down-timer-751**
Responsive is added.

**Comment by tobySolutions** [comment]
Sorry, I have to close this due to merge conflicts.

**Pull request closed without merging**
