### PR TITLE
added interactive-card-game file and css

### LINKED ISSUE #701: Kitchen Sink - Interactive Card Game
### Title:
Add Interactive Card Game Feature

### Description:
I suggest adding an interactive card game feature to the application. This feature would involve a card game where users can shuffle and interact with cards.

can you please assign me this Issue??

### Additional information

- [X] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by onlybond**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [x] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

resolve #701

### CODE REVIEW

**Review by tobySolutions — APPROVED** [review]
LGTM!

**Comment by tobySolutions** [comment]
Hey there @onlybond, could you maybe resolve your merge conflicts?

**Comment by Drex72** [comment]
@tobySolutions , are there still merge conflicts in this pr, because i cant see any from my end

**Comment by onlybond** [comment]
> Hey there @onlybond, could you maybe resolve your merge conflicts?

sure let me see

**Comment by onlybond** [comment]
@tobySolutions hey the conflicts are regarding the change in style.css, it is making a conflict because i have added my own css for this program in that style.css, is that acceptable??

**Comment by Timonwa** [comment]
> @tobySolutions hey the conflicts are regarding the change in style.css, it is making a conflict because i have added my own css for this program in that style.css, is that acceptable??

Hi @onlybond. I don't know what you mean by acceptable. But the conflict is rising because you and someone else made changes to the same line in the CSS file. So you have to merge the new changes with yours without any issues arising from both.

**Pull request closed without merging**
