### PR TITLE
Calculator example added

### PR DESCRIPTION
**Pull request by oliverloops**
**Please describe the changes this PR makes and why it should be merged:**
A new example added to kitchen sink, extending Million's use cases

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
@oliverloops amazing work! make sure to format w/ prettier + wrap the `Screen` component in a block

**Comment by oliverloops** [comment]
Sure!, I'll update the PR soon

**Comment by oliverloops** [comment]
I already formatted with prettier and added the block to `Screen` component. I also I added a react bare bones todo list example to complement

**Comment by aidenybai** [comment]
amazing work @oliverloops

**Pull request merged**
