### PR TITLE
Hover & Focus state for Social Icons 

### PR DESCRIPTION
**Pull request by adetyaz**
**Please describe the changes this PR makes and why it should be merged:**

This is for issue #634 

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Good job @adetyaz!

**Comment by adetyaz** [comment]
Thanks.

**Comment by tobySolutions** [comment]
Could you maybe push again, but this time just commit the file that you changed? For example, I can see that you have 18 files changed at the moment, most of it are formatting stuff by Prettier

**Comment by adetyaz** [comment]
Alright I'll do that. Can it be tomorrow please I'm already tucked in

**Pull request closed without merging**
