### PR TITLE
Fixes: Added the pokemon app #718

### LINKED ISSUE #718: Kitchen Sink : Pokemon App
### Describe the feature

This app will show all the pokemons and their stats and Evolutions.

Please assign me this for the **hacktoberfest_2023**

### Additional information

- [x] Would you be willing to help implement this feature?

### PR DESCRIPTION
**Pull request by sushilmagare10**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

added the Pokemon app that shows all the Pokemons
Resolves #718 

pokemon

### CODE REVIEW

**Review by tobySolutions — COMMENTED** [review]
Hey there @sushilmagare10, can you maybe review your implementation of the paragraph summarizer? 

The input state has a weird behavior:

https://github.com/aidenybai/million/assets/96334363/455a45a8-1fde-48f2-92d4-bd4302c1b4b1

**Comment by sushilmagare10** [comment]
The problem is when the API key is exposed the OpenAI team deletes it @tobySolutions 
can I add the env file without the git ignore without having the env
The mail i got from the OpenAI
openai mail

**Comment by tobySolutions** [comment]
> The problem is when the API key is exposed the OpenAI team deletes it @tobySolutions 
> can I add the env file without the git ignore without having the env
> The mail i got from the OpenAI
> openai mail
> 
> 

Hmm, maybe you can find an alternative 🤔🤔🤔

**Comment by tobySolutions** [comment]
Closing this for now.

**Pull request closed without merging**
