### PR TITLE
docs: translate the blog to french

### PR DESCRIPTION
**Pull request by chrioniep**
**This pull request  add french translation of the blog**

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
Could you review this, please? This page is supposed have the titles of the blog be in French. Thank you.

Screenshot 2024-01-31 at 15 16 46

**Comment by chrioniep** [comment]
> Could you review this, please? This page is supposed have the titles of the blog be in French. Thank you.
> 
> Screenshot 2024-01-31 at 15 16 46


The blog titles are supposed to change when you switch the language using the button at the bottom left, aren't they ?

Screenshot 2024-01-31 at 15 54 26

**Comment by tobySolutions** [comment]
Let me check @chrioniep. Thanks!

**Review by tobySolutions — APPROVED** [review]
LGTM! Thanks for all the work.

**Pull request merged**
