### PR TITLE
added calendar app

### PR DESCRIPTION
**Pull request by ATREAY**
**Please describe the changes this PR makes and why it should be merged:**

added calendar app to Kitchen sink and this PR pertains the issue #608(Kitchen Sink: Build A Calendar App)

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by Timonwa** [comment]
@ATREAY, thank you for the PR. I don't think this is what @tobySolutions meant when he said you should build a calendar app. The app is supposed to allow one to create events and reminders, the way Google calender does, am I right Tobi?

**Comment by ATREAY** [comment]
Hey @Timonwa, my bad for not getting the task, but let's wait and see what @tobySolutions suggests, and I'll make the changes based on that.

**Comment by Timonwa** [comment]
Sure, no problem.

**Comment by tobySolutions** [comment]
Um, yes @ATREAY. Timonwa is right. You can make your changes based on her feedback 😁

**Comment by ATREAY** [comment]
Ok @tobySolutions, I will make the changes accordingly.

**Comment by ATREAY** [comment]
Hey @tobySolutions, I'm having trouble with Vercel deployment. I'm not sure why, as I've run `pnpm i` correctly, but when I try `pnpm build` I'm hitting this error.
image

**Comment by tobySolutions** [comment]
Hey there @ATREAY! Sorry, what errors are you hitting? Also, can you check out your push? It looks like you have merge conflicts.

**Comment by ATREAY** [comment]
"Hey @tobySolutions, I've sorted out the conflict. Can you please check it out?"

**Comment by ATREAY** [comment]
Sure thing, @Timonwa! I'll get to work on it and redo the changes.

**Comment by ATREAY** [comment]
Hi @Timonwa and @Timonwa, I've made the necessary updates. Could you please take a look when you have a moment?

**Comment by tobySolutions** [comment]
Hey there @ATREAY! Good work. Could you maybe try resolving the merge conflict you have? Thanks!

**Comment by ATREAY** [comment]
Hey @tobySolutions, could you check it out? I've fixed the merge conflict.

**Comment by tobySolutions** [comment]
> Hey @tobySolutions, could you check it out? I've fixed the merge conflict.

Awesome! Thanks. I'm reviewing it now.

**Review by tobySolutions — APPROVED** [review]
LGTM! Good work!

**Pull request merged**
