### PR TITLE
Kitchen Sink : 15 puzzle game

### PR DESCRIPTION
**Pull request by sukritmalpani**
**Please describe the changes this PR makes and why it should be merged:**

Here is the working demo of the game.
[Screencast from 2023-10-07 22-54-21.webm](https://github.com/aidenybai/million/assets/119888457/19127904-41aa-445e-82e5-ca86e1dbb708)

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by Timonwa — CHANGES_REQUESTED** [review]
This looks good. It would have been nicer if you used the [`<For />` API](https://million.dev/docs/for) from Million.js to render the tiles.

Also, please resolve your merge conflicts.

**Comment by sukritmalpani** [comment]
@Timonwa <For /> is not working in my block and my tiles are not getting rendered.I have resolved the conflicts,can you please review the PR.Thanks for your feedback.

**Comment by Timonwa** [comment]
No problem @sukritmalpani 
@tobySolutions, this is ready for merge.

**Review by tobySolutions — COMMENTED** [review]
Could you maybe try using the block function on the borard, maybe?

**Comment by sukritmalpani** [comment]
@tobySolutions Thanks for your feedback.Surely,I did try using block on board component but the tiles are not getting rendered.

**Comment by tobySolutions** [comment]
Hey there @sukritmalpani, thank you very much for your contribution! Can you maybe resolve your merge conflicts? Thank you.

**Pull request closed without merging**
