### PR TITLE
feat: add i18n to docs

### PR DESCRIPTION
**Pull request by tobySolutions**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [x] Setup i18n according to Nextra docs
- [x] Fix 404 pages routing issues
- [x] Add Scaffold to support Chinese, French, Spanish
- [x] Add Scaffold to support Chinese, French, Spanish for blogs
- [ ] Open issues to make all the translations needed
- [x] Fix AI page being weird

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Oh man, 89 files?

**Comment by tobySolutions** [comment]
> Oh man, 89 files?

Yep yep! I have been busy actually.

**Comment by tobySolutions** [comment]
Can you help review this @aidenybai? Thanks!

**Comment by tobySolutions** [comment]
Thanks for the review @aidenybai 🙌

**Pull request merged**
