### PR TITLE
Emoji picker added

### LINKED ISSUE #620: Kitchen Sink: Build A Emoji Picker
Build an emoji picker that lets users easily insert emojis into text inputs that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

### PR DESCRIPTION
**Pull request by Roar022**
## Description of Changes:
In this PR, I have implemented a feature that allows users to insert emojis in between their text input using React, million.js, and TypeScript. This feature enhances the user experience by adding a fun and expressive way to convey emotions and reactions in text.

## Why it should be merged:
- **Improved User Experience:** Emojis are a widely recognized form of expression in modern communication. By enabling users to easily insert emojis into their text input, we enhance the overall user experience and make the application more engaging and user-friendly.

- **Expressive Communication:** Emojis provide a way for users to convey emotions and reactions effectively, which is particularly important in social or messaging applications. This feature enables users to express themselves more authentically.

- **Bug-Free Implementation:** I have thoroughly tested the feature to ensure it functions as intended and does not introduce any new bugs or issues. This ensures that merging this PR will not negatively impact the existing codebase.

## Demo Video:

https://github.com/aidenybai/million/assets/111555339/f4ad7ede-f6fb-42eb-8285-0ee662b4c02c

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

## Additional Note:
I believe that merging this PR will bring a valuable addition to our project, enhancing user experience and further solidifying our repository's reputation for innovation and user-friendly features. I look forward to feedback and collaboration from the team to refine and finalize this enhancement. Thank you for considering this PR.

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @Roar022, you seem to be having a build error, that is why this is failing. could you run `pnpm run build` on your local host, to view the errors and then try to fix them?

**Review by tobySolutions — COMMENTED** [review]
Hey there @Roar022 😁. Can you maybe try the things @Timonwa suggested to maybe track down why the deployment of your PR is failing?

**Comment by Roar022** [comment]
@Timonwa @tobySolutions I have Fixed the bug. Please review my PR.

**Comment by tobySolutions** [comment]
Awesome! Reviewing now

**Review by tobySolutions — APPROVED** [review]
Awesome!!! LGTM!!!

**Pull request merged**
