### PR TITLE
Complete Books_Store [user , admin] Website 

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
complete user , Admin ------ functionalities

Sign up , Login using JWT Authentication; Forgot password_Uisng node mailer

after user logged in then in his page , the books which was posted by the admin will be present, user can download and read it ;

Serach Functionality-----
User can search Any books based on his interest ----for this I am using Google API;

and User can request a book to the admin , in case if he want any books ;

from the ADMIN-----
he can see all the users , he can post the books , delete the books , Update the books and he can also view all the requests made by all the users with his names and he can resolve those ;

and this is build with good Ui , I am using react-toastify library and Bootstrap, CSS , Nodejs , Mongodb , express , React.js

once please check and merge it , Kindly inform for any modifications hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
User Side -------------------



Uploading USER side compressed.mp4…

**Comment by Bharath-KumarReddy** [comment]
User side-----------





https://github.com/aidenybai/million/assets/127650446/b20272fd-6262-47d6-8d27-0c0cc38f8dd8

**Comment by Bharath-KumarReddy** [comment]
Admin side --------



https://github.com/aidenybai/million/assets/127650446/2a898cd9-fb8f-4833-811b-d386d795496b

**Comment by Bharath-KumarReddy** [comment]
Once please check this and merge it , Kindly inform for any modifications   hacktoberfest_23 : )

**Review by tobySolutions — COMMENTED** [review]
I think you're doing the same thing you did in PR #736. For your large scale projects like these; I'd suggest deploying them somewhere else and you provide a link to the deployed version and the github in a react component in a new file in the `/examples` folder; so we can see them in production and review the code to see your usage of Million.js.

**Pull request closed without merging**
