### PR TITLE
Feat/url shortner

### PR DESCRIPTION
**Pull request by Abhishek-Mallick**
**Please describe the changes this PR makes and why it should be merged:**
This PR aims to demonstrate a url-shortner example using million incorporated with a shrcto API.

**Status**
Closes : https://github.com/aidenybai/million/issues/625

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

https://github.com/aidenybai/million/assets/106394426/1a3d8aae-b3d6-4942-b3d1-40e31f6a5d85

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by deeola** [comment]
LGTM

**Review by deeola — APPROVED** [review]

**Comment by Timonwa** [comment]
Hi @Abhishek-Mallick,  the purpose of this exercise is to show how to use Million.js in different instance.  Please incorporate Million.js into your project.

**Comment by Abhishek-Mallick** [comment]
Hey @Timonwa, I have made the necessary changes https://github.com/aidenybai/million/pull/664
- [x] Incorporated million
- [x] Component functions as before

**Review by tobySolutions — APPROVED** [review]
LGTM!!!

**Pull request merged**
