### PR TITLE
Playground: create and rename files

### LINKED ISSUE #370: Create New Files
**Description:**

Implement a feature that allows users to create new files within the playground. This feature should be intuitive and easy to use.

**Acceptance Criteria:**

- [ ] User can create a new file through a clearly marked interface.
- [ ] The new file is added to the file system and is editable by the user.

### PR DESCRIPTION
**Pull request by brunoeduardodev**
Closes #370 #371

This PR adds improvements on the tabs by enabling *Create*, *Rename* and *Removing* files.

### CODE REVIEW

**Comment by tobySolutions** [comment]
> right now the only problem with the current state of this PR is: renaming a file is changing the tab order, making the renamed tab go to the last tab, 
> 
> this is not seeing to be a very small thing since sandpack doesn't have a native "rename" support, we are basically creating a new file (keeping the code) and deleting the old one, also we don't have a direct control on the `visibleFiles` api, which I'm using to show the tabs.
> 
> there's a tricky solution that seemed to work:
> 
> (close all the tabs on the right, open the renamed file (this will open a new tab), re-open all the tabs that were on the right, call open on the renamed file again (switch focus back), delete old file
>  
> image
> 
> here I create a list of actions that I need to execute after a file is created, and then I execute step by step.
> I can't execute all this actions right inside the `onRename` function since the `openFile` & `closeFile` are on the end of the day just a set state, and these actions won't "compound" (only the last action would execute)
> 
> do you have thoughts?
> 
> on my end this implementation doesn't create flashes or weird UI changes
> 

Hmm, interesting. Can you make a short video to demo this?

Yo, check this out @aidenybai.

**Comment by brunoeduardodev** [comment]
short demo:

https://github.com/aidenybai/million/assets/50559336/811ff52b-dcff-43fc-bdf5-a012ce64a585

**Comment by brunoeduardodev** [comment]
yeah, it would be very cool!

**Comment by tobySolutions** [comment]
Awesome!

**Comment by brunoeduardodev** [comment]
cool, so I'm already on the discord if you guys wanna talk about this, aside of that is there anything else missing on this PR?

I want to submit another PR with Console already with this updates as base

**Comment by tobySolutions** [comment]
> cool, so I'm already on the discord if you guys wanna talk about this, aside of that is there anything else missing on this PR?
> 
> I want to submit another PR with Console already with this updates as base

Let's chat on the playground channel in the Discord. 🏃🏃🏃

**Comment by brunoeduardodev** [comment]
any thoughts on showing the file path on the tab? 
https://www.loom.com/share/60abcddfa6604950b958600444649f32?sid=f090ef51-1254-4814-8551-0204a0684f1b

**Comment by brunoeduardodev** [comment]
I also need to know if there's some preferred icon library to use for "close" and "add" icons,
aside from that, I don't think there's much left to do in this PR, waiting for reviews on it

**Comment by brunoeduardodev** [comment]
also, for reference about keyboard navigation, you can switch focus on tabs pressing `Tab`, while focusing on a tab, pressing `Space` will select it (make it the active code shown on the editor), and pressing `Enter` will start renaming, this is the behaviour of macos Finder, and seem to be intuitive, any thoughts?

**Comment by aidenybai** [comment]
LGTM :) @GuiBibeau?

**Review by aidenybai — APPROVED** [review]

**Review by GuiBibeau — APPROVED** [review]
LGTM 🔥

**Pull request merged**
