### PR TITLE
feat: add expense tracker to kitchen skin

### PR DESCRIPTION
**Pull request by vimode**
**Please describe the changes this PR makes and why it should be merged:**

This PR adds **Expense tracker** example to the list of Kitchen Sink examples as per #606 

I ran the `pnpm cleanup` command and it modified a lot of files, but I only pushed the changes for this project file and nothing more, hope thats okay. 

The `pnpm lint` and `pnpm test` command and all seems OK. 

My knowledge of TS and million is very basic so please recommend fixes as needed. 

If there is any missing feature in the current implementation of the project or some logic that seems odd or need fixing, I am ready to work on it as needed. 

Thank you.

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by tobySolutions** [comment]
> **Please describe the changes this PR makes and why it should be merged:**
> 
> This PR adds **Expense tracker** example to the list of Kitchen Sink examples as per #606
> 
> I ran the `pnpm cleanup` command and it modified a lot of files, but I only pushed the changes for this project file and nothing more, hope thats okay.
> 
> The `pnpm lint` and `pnpm test` command and all seems OK.
> 
> My knowledge of TS and million is very basic so please recommend fixes as needed.
> 
> If there is any missing feature in the current implementation of the project or some logic that seems odd or need fixing, I am ready to work on it as needed.
> 
> Thank you.
> 
> **Status**
> 
> * [x]  Code changes have been tested against prettier, or there are no code changes
> * [x]  I know how to update typings and have done so, or typings don't need updating
> 
> **Semantic versioning classification:**
> 
> * [x]  This PR **only** includes non-code changes, like changes to documentation, README, etc.

Sure thing! @vimode! Reviewing now

**Review by tobySolutions — APPROVED** [review]
LGTM! Interesting usage of the block function though. Is there a reason as to your usage in just the `ExpenseItem`

**Comment by vimode** [comment]
Hey @tobySolutions 

Thank you for the review. 

If I use the block function on the whole app. the way I have the form inputs be handled by the parent component causes the whole app to re-render(?) when one starts typing, losing focus on the input on every key stroke. 

But I think moving the state locally to the component should fix that issue. Let me try and fix this accordingly.

**Comment by vimode** [comment]
Hey @tobySolutions I millionified it a bit more! 🦁

**Review by Timonwa — APPROVED** [review]

**Comment by tobySolutions** [comment]
Good work @vimode!

**Review by tobySolutions — APPROVED** [review]
LGTM!!

**Pull request merged**
