### PR TITLE
feat: add prelim code frames

### PR DESCRIPTION
**Pull request by aidenybai**
**Please describe the changes this PR makes and why it should be merged:**

Partially addresses #342's point #1

image

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
I'm going to merge this as a hotfix. Will open a subsequent PR for fix code qual

**Comment by tobySolutions** [comment]
Everything here works now, right?

**Comment by aidenybai** [comment]
yup

**Comment by tobySolutions** [comment]
> yup

Ok, perfect!

**Pull request merged**
