### PR TITLE
refactor: better for loops, enums are auto incrementing

### PR DESCRIPTION
**Pull request by willdoescode**
**Please describe the changes this PR makes and why it should be merged:**

**Status**

- [ ] Code changes have been tested against prettier, or there are no code changes
- [ ] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by hyrious** [comment]
I'm not sure whether forEach or for-of are "better".

**Comment by aidenybai** [comment]
I would merge this PR in terms of readability, but this for loop handles a critical role in executing functions (the `workStack`) and `forEach` has significantly worse performance compared to for loop: ([ref](https://stackoverflow.com/questions/9746579/for-loop-vs-foreach-performance-in-javascript-and-credibility-of-jsperf-results))

**Comment by willdoescode** [comment]
yeah I'll change it to a for of

**Comment by aidenybai** [comment]
Closed for perf contrainsts

**Pull request closed without merging**
