### PR TITLE
hotfix: contexts

### PR DESCRIPTION
**Pull request by aidenybai**
**Please describe the changes this PR makes and why it should be merged:**

This PR fixes contexts by reimplementing the root system to portal based system.

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [x] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Two things that come to mind are:
1. This approach might break SSR.
2. This introduces the possibility of nested portals right? Do we need to avoid that scenario?

Otherwise generally this looks good, hard for me to examine in more detail without more test apps though.

**Comment by AbhiPrasad** [comment]
Is there a way we can feature flag this to make it easier to test? Like we switch to the portal approach with an opt-in flag, ask people to test and then switch to this once we have more confidence.

**Review by oliverloops — APPROVED** [review]
I reviewed the core block re-implementation and see everything fine, I just have a couple of questions around this portal based system:

- What's the main purpose or migrate from the old one?
- This could make harder to make it compatible with 3rd party UI libraries and the future cross file blocks feature?

**Comment by aidenybai** [comment]
going to run some beta tests

**Pull request merged**
