### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by cyberviking5**
**Please describe the changes this PR makes and why it should be merged:**
I have made a weather app which shows the temperature of the city entered along with the weather description . It is done in typescript and all the correct methods are followed .
Screenshot from 2023-10-02 19-17-30
Screenshot from 2023-10-02 21-34-30

If you want any changes please inform me :)

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
Please run `pnpm run cleanup` @cyberviking5

**Comment by cyberviking5** [comment]
@aidenybai please check it and let me know if i have make any more changes :) . Thanks !

**Review by tobySolutions — CHANGES_REQUESTED** [review]
Can you please remove console logs @cyberviking5? Thanks. Also, did you try using `block` on the main Weather component being exported?

**Comment by cyberviking5** [comment]
@tobySolutions i have removed the consoles and also i did try using block in the main weather components but it was showing some error . Please review the changes and let me know if you want any more changes :)

**Comment by cyberviking5** [comment]
@tobySolutions please review the changes and please let me know if i have to make any changes :)

**Review by tobySolutions — APPROVED** [review]
LGTM!!

**Pull request merged**
