### PR TITLE
Currency Convertor Added

### LINKED ISSUE #604: Kitchen Sink: Build A Currency Converter
Build a currency converter with real-time exchange rates that you'll add to the kitchen sink. Feel free to use any existing projects of yours or start one from scratch.

For more information about the Kitchen sink; check out:

- https://sink.million.dev/
- https://github.com/aidenybai/million/blob/main/packages/kitchen-sink/README.md

N.B: **Upon PR review, your usage of Million.js is a plus**

### PR DESCRIPTION
**Pull request by Roar022**
I have added a Currency Convertor using Million.js, Reactjs and Typescript. It allows user to convert one currency to another.
## Resolves #604 

**Status**

- [x] Code changes have been tested against prettier, or there are no code changes
- [x] I know how to update typings and have done so, or typings don't need updating

**Semantic versioning classification:**

- [ ] This PR changes the codebase
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
  - [ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by aidenybai** [comment]
Please cleanup your code @Roar022

**Comment by Roar022** [comment]
> Please cleanup your code @Roar022

Form This you mean optimization of code?

**Review by tobySolutions — CHANGES_REQUESTED** [review]
I think what @aidenybai meant was for you to remove the many commented code.

**Comment by Roar022** [comment]
> I think what @aidenybai meant was for you to remove the many commented code.

Ohh!!, I am really sorry for this mistake. Fixing it right now.

**Comment by tobySolutions** [comment]
> > I think what @aidenybai meant was for you to remove the many commented code.
> 
> Ohh!!, I am really sorry for this mistake. Fixing it right now.

Awesome! Sure thing.

**Comment by Roar022** [comment]
@tobySolutions @aidenybai Please review my changes. If you want any changes, please let me know.

**Comment by Timonwa** [comment]
@Roar022 could you edit your button name from `CurrencyConverter` to `currency-converter`, so it can be the same as other buttons?

**Comment by tobySolutions** [comment]
Hey there @Roar022! Thank you very much for your PR. You have a duplication though, can you maybe delete one of the files?

https://github.com/aidenybai/million/assets/96334363/eb62ff11-01ea-49f0-80a3-645e39145ef1

**Comment by Roar022** [comment]
Thank you for your feedback and for reviewing my PR. I apologize for the duplication in the files. I have updated the PR.

**Review by tobySolutions — APPROVED** [review]

**Review by tobySolutions — APPROVED** [review]
LGTM!!

**Comment by elibroftw** [comment]
The currency does not update  onChange with a debounce.

**Pull request merged**
